language: cpp
dist: trusty
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update

install:
  - sudo apt-get install qt58base qt58svg qt58charts-no-lgpl qt58xmlpatterns
  - source /opt/qt58/bin/qt58-env.sh



script:
  - /opt/qt58/bin/qmake testv2.pro  #!PREFIX=/usr
  - make
  - pwd
  - ls /home/travis/build/andrii-velychko-GL/QtAppTest/
  - ls /home/travis/build/andrii-velychko-GL/QtAppTest/testv2
  - ls /home/travis/build/andrii-velychko-GL/QtAppTest/Makefile
  
deploy:
  provider: releases
  edge: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: /home/travis/build/andrii-velychko-GL/QtAppTest/*
  skip_cleanup: true
  on:
    tags: off
    tag_name: 'test'


