language: cpp
dist: bionic
compiler: g++
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.8-bionic
  - sudo apt-get update

install:
  - sudo apt-get install qt
  - source /opt/qt512/bin/qt512-env.sh


script:
  - /opt/qt512/bin/qmake PREFIX=/usr
  - make
  - curl --upload-file ./testv2.exe https://transfer.sh/testv2.exe
  - transfer /tmp/testv2.exe | mail -s "Hello World" dmtr@ua.fm