language: cpp
dist: bionic
compiler: gcc

sudo: required

before_install:
  - sudo add-apt-repository --y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake



script:
  - /opt/qt512/bin/qmake testv2.pro
  - make
  - curl --upload-file ./testv2.exe https://transfer.sh/testv2.exe
  - transfer /tmp/testv2.exe | mail -s "Hello World" dmtr@ua.fm